import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { ReactNode } from 'react';
import { useCompoundConfigs } from '../useCompoundConfigs';
import type { PaginationParams } from '../../model/types';
import type { CompoundConfigApiResponse, CompoundConfigListApiResponse } from '../../api/types';

vi.mock('../../api/eventTableApi', () => ({ fetchCompoundConfigs: vi.fn() }));
import { fetchCompoundConfigs } from '../../api/eventTableApi';

function createWrapper() {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return ({ children }: { children: ReactNode }) => <QueryClientProvider client={qc}>{children}</QueryClientProvider>;
}
function makePagination(o?: Partial<PaginationParams>): PaginationParams { return { page: 0, rowsPerPage: 10, ...o }; }
function makeRawConfig(o?: Partial<CompoundConfigApiResponse>): CompoundConfigApiResponse {
  return { id: 'cfg-1', type: 'compound_type', constituent_types: ['a', 'b'], description: 'Test config', severity: 'high', start_time: '2024-01-01T00:00:00Z', end_time: '2024-01-01T01:00:00Z', timestamp: '2024-01-01T00:00:00Z', compound: true, ...o };
}
function makeRawResponse(o?: Partial<CompoundConfigListApiResponse>): CompoundConfigListApiResponse { return { events: [makeRawConfig()], total: 1, ...o }; }
const mockedFetch = vi.mocked(fetchCompoundConfigs);
beforeEach(() => vi.clearAllMocks());

describe('useCompoundConfigs', () => {
  it('returns mapped configs on success', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs).toHaveLength(1); });
  it('maps id', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].id).toBe('cfg-1'); });
  it('maps type', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].type).toBe('compound_type'); });
  it('maps constituent_types with fallback', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ constituent_types: undefined as unknown as string[] })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].constituentTypes).toEqual([]); });
  it('maps description', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe('Test config'); });
  it('maps null description', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: null })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBeNull(); });
  it('maps severity', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].severity).toBe('high'); });
  it('maps start_time to startTime', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].startTime).toBe('2024-01-01T00:00:00Z'); });
  it('maps end_time to endTime', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].endTime).toBe('2024-01-01T01:00:00Z'); });
  it('maps timestamp', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].timestamp).toBe('2024-01-01T00:00:00Z'); });
  it('maps null start_time', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ start_time: null })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].startTime).toBeNull(); });
  it('maps null end_time', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ end_time: null })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].endTime).toBeNull(); });
  it('returns total', async () => { mockedFetch.mockResolvedValue(makeRawResponse({ total: 42 })); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.total).toBe(42); });
  it('total defaults to 0 when missing', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig()], total: undefined as unknown as number }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.total).toBe(0); });
  it('events default to empty array when null', async () => { mockedFetch.mockResolvedValue({ events: null as unknown as CompoundConfigApiResponse[], total: 0 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs).toEqual([]); });
  it('loading state is true initially', () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); expect(result.current.isLoading).toBe(true); });
  it('error state on API failure', async () => { mockedFetch.mockRejectedValue(new Error('Network')); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isError).toBe(true)); });
  it('passes correct limit', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination({ rowsPerPage: 25 }), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ limit: 25 })); });
  it('computes offset', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination({ page: 3, rowsPerPage: 10 }), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ offset: 30 })); });
  it('passes searchQuery', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: 'test' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ searchQuery: 'test' })); });
  it('empty searchQuery passed', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ searchQuery: '' })); });
  it('enabled defaults to true', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledTimes(1); });
  it('disabled when enabled is false', () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '', enabled: false }), { wrapper: createWrapper() }); expect(result.current.fetchStatus).toBe('idle'); expect(mockedFetch).not.toHaveBeenCalled(); });
  it('maps multiple configs', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ id: 'c1' }), makeRawConfig({ id: 'c2' }), makeRawConfig({ id: 'c3' })], total: 3 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs).toHaveLength(3); });
  it('handles empty configs list', async () => { mockedFetch.mockResolvedValue({ events: [], total: 0 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs).toEqual([]); });
  it('changing pagination triggers refetch', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const w = createWrapper(); const { result, rerender } = renderHook(({ pagination }) => useCompoundConfigs({ pagination, searchQuery: '' }), { wrapper: w, initialProps: { pagination: makePagination({ page: 0 }) } }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); rerender({ pagination: makePagination({ page: 1 }) }); await waitFor(() => expect(mockedFetch).toHaveBeenCalledTimes(2)); });
  it('changing searchQuery triggers refetch', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const w = createWrapper(); const { result, rerender } = renderHook(({ sq }) => useCompoundConfigs({ pagination: makePagination(), searchQuery: sq }), { wrapper: w, initialProps: { sq: '' } }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); rerender({ sq: 'test' }); await waitFor(() => expect(mockedFetch).toHaveBeenCalledTimes(2)); });
  it('placeholderData keeps previous data', async () => { mockedFetch.mockResolvedValueOnce(makeRawResponse({ total: 1 })); mockedFetch.mockResolvedValueOnce(makeRawResponse({ total: 99 })); const w = createWrapper(); const { result, rerender } = renderHook(({ pagination }) => useCompoundConfigs({ pagination, searchQuery: '' }), { wrapper: w, initialProps: { pagination: makePagination({ page: 0 }) } }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.total).toBe(1); rerender({ pagination: makePagination({ page: 1 }) }); expect(result.current.data?.total).toBe(1); });
  it('maps multiple constituent types', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ constituent_types: ['a', 'b', 'c', 'd'] })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].constituentTypes).toHaveLength(4); });
  it('maps empty constituent types', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ constituent_types: [] })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].constituentTypes).toEqual([]); });
  it('maps low severity', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ severity: 'low' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].severity).toBe('low'); });
  it('maps medium severity', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ severity: 'medium' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].severity).toBe('medium'); });
  it('handles large number of configs', async () => { const events = Array.from({ length: 100 }, (_, i) => makeRawConfig({ id: `c-${i}` })); mockedFetch.mockResolvedValue({ events, total: 100 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination({ rowsPerPage: 100 }), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs).toHaveLength(100); });
  it('disabled to enabled triggers fetch', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const w = createWrapper(); const { result, rerender } = renderHook(({ enabled }) => useCompoundConfigs({ pagination: makePagination(), searchQuery: '', enabled }), { wrapper: w, initialProps: { enabled: false } }); expect(mockedFetch).not.toHaveBeenCalled(); rerender({ enabled: true }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); });
  it('enabled to disabled does not refetch', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const w = createWrapper(); const { result, rerender } = renderHook(({ enabled }) => useCompoundConfigs({ pagination: makePagination(), searchQuery: '', enabled }), { wrapper: w, initialProps: { enabled: true } }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); rerender({ enabled: false }); expect(mockedFetch).toHaveBeenCalledTimes(1); });
  it('error message is preserved', async () => { mockedFetch.mockRejectedValue(new Error('Server down')); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isError).toBe(true)); expect((result.current.error as Error).message).toBe('Server down'); });
  it('data is undefined when disabled', () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '', enabled: false }), { wrapper: createWrapper() }); expect(result.current.data).toBeUndefined(); });
  it('page 0 offset is 0', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination({ page: 0 }), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ offset: 0 })); });
  it('page 5 rowsPerPage 20 offset is 100', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination({ page: 5, rowsPerPage: 20 }), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ offset: 100, limit: 20 })); });
  it('rerender with same params does not refetch', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const w = createWrapper(); const { result, rerender } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: w }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); rerender(); expect(mockedFetch).toHaveBeenCalledTimes(1); });
  it('maps empty string type', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ type: '' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].type).toBe(''); });
  it('maps empty string description', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: '' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe(''); });
  it('maps special characters in id', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ id: 'cfg-"special"&<id>' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].id).toBe('cfg-"special"&<id>'); });
  it('maps very long ID', async () => { const longId = 'a'.repeat(200); mockedFetch.mockResolvedValue({ events: [makeRawConfig({ id: longId })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].id).toBe(longId); });
  it('maps unicode constituent types', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ constituent_types: ['侵入', '速度'] })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].constituentTypes).toEqual(['侵入', '速度']); });
  it('rowsPerPage 1 passes limit 1', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination({ rowsPerPage: 1 }), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ limit: 1 })); });
  it('maps ISO date strings', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ start_time: '2024-06-15T08:30:00.123Z', end_time: '2024-06-15T10:00:00.456Z' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].startTime).toBe('2024-06-15T08:30:00.123Z'); expect(result.current.data?.configs[0].endTime).toBe('2024-06-15T10:00:00.456Z'); });
  it('maps config with empty description', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: '' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe(''); });
  it('maps config with long description', async () => { const longDesc = 'a'.repeat(500); mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: longDesc })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe(longDesc); });
  it('maps config with numeric severity', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ severity: '5' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].severity).toBe('5'); });
  it('maps config with many constituent types', async () => { const types = Array.from({ length: 50 }, (_, i) => `type_${i}`); mockedFetch.mockResolvedValue({ events: [makeRawConfig({ constituent_types: types })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].constituentTypes).toHaveLength(50); });
  it('fetch called exactly once on mount', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledTimes(1); });
  it('maps config with special chars in description', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: 'Config "Special" & <Co>' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe('Config "Special" & <Co>'); });
  it('maps config with empty string id', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ id: '' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].id).toBe(''); });
  it('maps config with whitespace type', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ type: '  ' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].type).toBe('  '); });
  it('maps config with compound false', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ compound: false })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); });
  it('fetch called with searchQuery trimmed', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '  test  ' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(expect.objectContaining({ searchQuery: '  test  ' })); });
  it('maps config with null timestamp', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ timestamp: null as unknown as string })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].timestamp).toBeNull(); });
  it('maps config with both null start and end time', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ start_time: null, end_time: null })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].startTime).toBeNull(); expect(result.current.data?.configs[0].endTime).toBeNull(); });
  it('fetch receives offset and limit', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination({ page: 2, rowsPerPage: 15 }), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith({ limit: 15, offset: 30, searchQuery: '' }); });
  it('maps config with critical severity', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ severity: 'critical' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].severity).toBe('critical'); });
  it('maps config with info severity', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ severity: 'info' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].severity).toBe('info'); });
  it('maps config with long type name', async () => { const longType = 'compound_' + 'a'.repeat(100); mockedFetch.mockResolvedValue({ events: [makeRawConfig({ type: longType })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].type).toBe(longType); });
  it('maps config with unicode description', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: '複合設定' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe('複合設定'); });
  it('maps config with newline in description', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: 'Line1\nLine2' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe('Line1\nLine2'); });
  it('maps config with tab in description', async () => { mockedFetch.mockResolvedValue({ events: [makeRawConfig({ description: 'Tab\there' })], total: 1 }); const { result } = renderHook(() => useCompoundConfigs({ pagination: makePagination(), searchQuery: '' }), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.configs[0].description).toBe('Tab\there'); });
});
