import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { ReactNode } from 'react';
import { useEventMetadata } from '../useEventMetadata';
import type { MetadataColumnRaw, EventMetadataApiResponse } from '../../api/types';

vi.mock('../../api/eventTableApi', () => ({ fetchEventMetadata: vi.fn() }));
import { fetchEventMetadata } from '../../api/eventTableApi';

function createWrapper() {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return ({ children }: { children: ReactNode }) => <QueryClientProvider client={qc}>{children}</QueryClientProvider>;
}
function makeRawColumn(o?: Partial<MetadataColumnRaw>): MetadataColumnRaw {
  return { field: 'severity', label: 'Severity', type: 'string', filterable: true, unique_values: ['high', 'low'], ...o };
}
function makeRawResponse(o?: Partial<EventMetadataApiResponse>): EventMetadataApiResponse {
  return { columns: [makeRawColumn()], ...o };
}
const mockedFetch = vi.mocked(fetchEventMetadata);
beforeEach(() => vi.clearAllMocks());

describe('useEventMetadata', () => {
  it('returns mapped columns on success', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data).toHaveLength(1); });
  it('maps field', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('severity'); });
  it('maps label', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].label).toBe('Severity'); });
  it('maps type', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].type).toBe('string'); });
  it('maps unique_values with fallback', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: undefined as unknown as (string | number)[] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([]); });
  it('maps unique_values as strings', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['high', 'low', 'medium'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['high', 'low', 'medium']); });
  it('maps unique_values as numbers', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [1, 2, 3] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([1, 2, 3]); });
  it('maps unique_values as mixed types', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['high', 1, 'low', 2] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['high', 1, 'low', 2]); });
  it('maps type as number', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ type: 'number' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].type).toBe('number'); });
  it('maps type as timestamp', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ type: 'timestamp' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].type).toBe('timestamp'); });
  it('maps type as boolean', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ type: 'boolean' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].type).toBe('boolean'); });
  it('loading state is true initially', () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); expect(result.current.isLoading).toBe(true); });
  it('error state on API failure', async () => { mockedFetch.mockRejectedValue(new Error('Network')); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isError).toBe(true)); });
  it('error message is preserved', async () => { mockedFetch.mockRejectedValue(new Error('Server down')); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isError).toBe(true)); expect((result.current.error as Error).message).toBe('Server down'); });
  it('maps multiple columns', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'severity' }), makeRawColumn({ field: 'status' }), makeRawColumn({ field: 'type' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data).toHaveLength(3); expect(result.current.data?.[1].field).toBe('status'); });
  it('handles empty columns list', async () => { mockedFetch.mockResolvedValue({ columns: [] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data).toEqual([]); });
  it('rerender does not refetch', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const w = createWrapper(); const { result, rerender } = renderHook(() => useEventMetadata(), { wrapper: w }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledTimes(1); rerender(); expect(mockedFetch).toHaveBeenCalledTimes(1); });
  it('fetch is called exactly once on mount', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledTimes(1); });
  it('maps column with empty unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([]); });
  it('maps column with large unique_values', async () => { const vals = Array.from({ length: 100 }, (_, i) => `val_${i}`); mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: vals })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toHaveLength(100); });
  it('maps column with empty field', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: '' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe(''); });
  it('maps column with empty label', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ label: '' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].label).toBe(''); });
  it('maps column with special characters in field', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'field."special"&<id>' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('field."special"&<id>'); });
  it('maps column with special characters in label', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ label: 'Label "Special" & <Co>' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].label).toBe('Label "Special" & <Co>'); });
  it('maps column with unicode field', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: '深刻度' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('深刻度'); });
  it('maps column with unicode label', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ label: '深刻度ラベル' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].label).toBe('深刻度ラベル'); });
  it('maps column with very long field name', async () => { const longField = 'f'.repeat(200); mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: longField })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe(longField); });
  it('maps column with very long label', async () => { const longLabel = 'L'.repeat(200); mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ label: longLabel })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].label).toBe(longLabel); });
  it('maps column with dot notation field', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'information.subfield' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('information.subfield'); });
  it('maps column with numeric unique_values including zero', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [0, 1, 2] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([0, 1, 2]); });
  it('maps column with negative numbers in unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [-1, -2, -3] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([-1, -2, -3]); });
  it('maps column with float numbers in unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [1.5, 2.5, 3.5] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([1.5, 2.5, 3.5]); });
  it('maps column with empty string in unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [''] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['']); });
  it('maps column with whitespace in unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['  '] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['  ']); });
  it('maps column with special chars in unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['test&special<>"'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['test&special<>"']); });
  it('maps many columns', async () => { const cols = Array.from({ length: 50 }, (_, i) => makeRawColumn({ field: `field_${i}`, label: `Label ${i}` })); mockedFetch.mockResolvedValue({ columns: cols }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data).toHaveLength(50); expect(result.current.data?.[49].field).toBe('field_49'); });
  it('data is undefined while loading', () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); expect(result.current.data).toBeUndefined(); });
  it('maps column with filterable true', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ filterable: true })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); });
  it('maps column with filterable false', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ filterable: false })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); });
  it('maps column with unique_values containing duplicates', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['high', 'high', 'low'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['high', 'high', 'low']); });
  it('maps column with newlines in label', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ label: 'Line1\nLine2' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].label).toBe('Line1\nLine2'); });
  it('maps column with tabs in label', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ label: 'Tab\there' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].label).toBe('Tab\there'); });
  it('maps column with mixed case field', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'SeverityField' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('SeverityField'); });
  it('maps column with underscores in field', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'event_type_field' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('event_type_field'); });
  it('maps column with numbers in field name', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'field123' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('field123'); });
  it('maps column with boolean unique_values as strings', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['true', 'false'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['true', 'false']); });
  it('maps column with timestamp unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['2024-01-01', '2024-06-15'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['2024-01-01', '2024-06-15']); });
  it('maps column with very large unique_values', async () => { const vals = Array.from({ length: 1000 }, (_, i) => `val_${i}`); mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: vals })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toHaveLength(1000); });
  it('fetch is called with no arguments', async () => { mockedFetch.mockResolvedValue(makeRawResponse()); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(mockedFetch).toHaveBeenCalledWith(); });
  it('maps column with empty string and number in unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['', 0, 'high'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['', 0, 'high']); });
  it('maps column with null unique_values fallback', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: null as unknown as (string | number)[] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([]); });
  it('maps column with very long unique_value string', async () => { const longVal = 'v'.repeat(500); mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [longVal] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([longVal]); });
  it('maps column with mixed numeric and string unique_values', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [1, 'two', 3, 'four'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([1, 'two', 3, 'four']); });
  it('maps column with single unique_value', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: ['only'] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual(['only']); });
  it('maps column with single numeric unique_value', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ unique_values: [42] })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].uniqueValues).toEqual([42]); });
  it('maps column with space in field name', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'event type' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('event type'); });
  it('maps column with hyphen in field name', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'event-type' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('event-type'); });
  it('maps column with dot and underscore in field', async () => { mockedFetch.mockResolvedValue({ columns: [makeRawColumn({ field: 'info.sub_field' })] }); const { result } = renderHook(() => useEventMetadata(), { wrapper: createWrapper() }); await waitFor(() => expect(result.current.isSuccess).toBe(true)); expect(result.current.data?.[0].field).toBe('info.sub_field'); });
});
